### ISSUE TITLE
IRC Tramp protocol on Tran 3016W 

### ISSUE THREAD

**Issue by RandyReover** [jhemcu/FC-ESC-Firmware#14]
I've trying to get IRC Tramp protocol work on Jhemcu Tran 3016, but it doesn't work.
So there are technical questions about Tramp implementation on this VTX:
1. Have you tested this VTX on BetaFlight/INav or ArduPilot? 
2. Could you provide with some dumps of IRC Tramp commands to your VTX? I'm trying to send following commands but the VTX just not answer (waiting about 3sec):
a) Init ('r' cmd): 0x0F, 0x72, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x81, 0x00
b) Get Config ('v' cmd): 0x0F, 0x76, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x85, 0x00

Commands sent by halfduplex UART with [9600bps, 8N1, not inverted, 5V logic level] characteristics, after command sent, uart is listening, but there is no any byte of response.
I'm able to provide Arduino project (tested on ArduinoMega2560Pro) to make tests, this project succesfully works with Eachine TX5258(in SmartAudio mode).
On Betaflight forums I've read about 'poor implementation of IRC Tramp and SmartAudio protocols', there are some workarounds with AKK/RDQ VTX's, but it doesn't work with Tran3016W.
So, could you provide working dumps of commands (or working code examples) to this VTX to get it switch power and channels by wire?

**Comment by jhemcu** [comment]
I have sent you the JSON file. Please refer to the attachment。Please do not make any modifications to the JSON file on your own, as this may prevent you from using image transmission correctly. You do not need to question whether it has been tested on BF and INAV, as this is necessary. If it cannot be used normally, why do we dare to ship in bulk. In addition, our product information can be downloaded from this website, or you can ask your seller for information.


&nbsp;https://github.com/jhemcu/FC-ESC-Firmware




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jhemcu/FC-ESC-Firmware"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 凌晨0:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[jhemcu/FC-ESC-Firmware] IRC Tramp protocol on Tran 3016W  (Issue #14)





 
I've trying to get IRC Tramp protocol work on Jhemcu Tran 3016, but it doesn't work.
 So there are technical questions about Tramp implementation on this VTX:
  
Have you tested this VTX on BetaFlight/INav or ArduPilot?
 
Could you provide with some dumps of IRC Tramp commands to your VTX? I'm trying to send following commands but the VTX just not answer (waiting about 3sec):
 a) Init ('r' cmd): 0x0F, 0x72, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x81, 0x00
 b) Get Config ('v' cmd): 0x0F, 0x76, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x85, 0x00
  
Commands sent by halfduplex UART with [9600bps, 8N1, not inverted, 5V logic level] characteristics, after command sent, uart is listening, but there is no any byte of response.
 I'm able to provide Arduino project (tested on ArduinoMega2560Pro) to make tests, this project succesfully works with Eachine TX5258(in SmartAudio mode).
 On Betaflight forums I've read about 'poor implementation of IRC Tramp and SmartAudio protocols', there are some workarounds with AKK/RDQ VTX's, but it doesn't work with Tran3016W.
 So, could you provide working dumps of commands (or working code examples) to this VTX to get it switch power and channels by wire?

**Comment by RandyReover** [comment]
Thanks, but I have this json and this file couldn't solve the problem, it just contains the range of channels and powers. I've used Betaflight (and later Ardupilot) and BF with this VTX (and json provided) has Offline status. I've tried to use my own (based on BF code) code to determine the problem, and the problem is in zero-responses from VTX. I send Init command, and have no response, I send Get_Config command and have no response(I've provided dumps of these packets/data frames sent to VTX). 
So my question - could you provide correct dumps/frames for these commands( for example, to get response from Eachine TX5258 I've send 0x00 before command and 0x00 after, in this case TX5258 answered(with not so correct packet, but it can be parsed and used) )? They are static, just queries to VTX, 16 bytes, first 0x0F, second - command (0x72 or 0x76), with static data in the packet, and static crc (depends on command - 0x81 or 0x85). But there is probably some trick - to send additional bytes before or after command to get response?

**Comment by RandyReover** [comment]
Additional information:
1. According to wiring diagram I've linked IRC/RXD pin/wire to my halfduplex uart port.
2. Used 9600bps, 8 databits, one stop bit configuration (8N1), 5v logic level. 
3. I've tried to used different baud rates from 9120 to 10080bps.
4. I've tried to use 8N2 configuration
5. I've tried to write 0x00 byte before, after and before and after command frame (known workaround for AKK/RDQ VTXs).
6. I've tried to not use crc in command frame.
7. The first command which sould be sent to IRC Tramp VTX - Init(0x72), to make VTX 
... and still get no response from VTX. 
- Probably I should TURN ON Tramp on VTX (on Eachine TX5258 - I should press button about 10sec to see flickering dot to TURN ON SmartAudio protocol), so please advise how to do it?
- Probably wiring diagram not so correct and I should wire to other pin?
So I'd like to see the video where this VTX wired and work with Betaflight/Ardupilot successfully switching channels/powers, just using JSON provided.

**Comment by RandyReover** [comment]
So now I'm able to confirm that IRC Tramp correctly works on JHEMCU Ruibet Tran3016W.
There was a problem with crc calcultation (there were difference between ArduPilot and Betaflight crc calculation, and ArduPilot procedure is correct (calc from second to 13th byte, crc is written to 14th byte)).
So, correct Init (0x72, 'r') command command dump:
0F 72 00 00 00 00 00 00 00 00 00 00 00 00 72 00
Received response: 
0F 72 EC 13 70 17 58 02 00 00 00 00 00 00 52 00
Correct GetConfig (0x76, 'v') command dump:
0F 76 00 00 00 00 00 00 00 00 00 00 00 00 76 00
Received response:
0F 76 78 16 19 00 00 00 00 00 00 00 00 00 1D 00
